databases:
  - name: menu_graphql_production
    databaseName: menu_graphql_production
    user: admin
    plan: free

services:
  - type: web
    name: menu_graphql_production
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: menu_graphql_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
